# Generated by Django 5.1.7 on 2025-04-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2047)),
                ('date', models.DateField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
