# Generated by Django 5.1.7 on 2025-04-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_artikel_date_alter_artikel_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artikel',
            new_name='Article',
        ),
    ]
