# Generated by Django 5.1.7 on 2025-04-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_article_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Artikel',
        ),
    ]
