# Generated by Django 5.1.7 on 2025-04-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_rename_article_artikel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-date']},
        ),
    ]
