# Generated by Django 5.1.7 on 2025-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_artikel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='content',
            field=models.TextField(),
        ),
    ]
