# Generated by Django 5.1.7 on 2025-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_artikel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='homepage/static/images'),
        ),
    ]
