# Generated by Django 5.1.7 on 2025-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_artikel_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='artikel',
            name='image_description',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
