# Generated by Django 5.1.7 on 2025-04-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_rename_picture_artikel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='image_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
