# Generated by Django 5.1.7 on 2025-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_artikel_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='image_description',
            field=models.TextField(blank=True),
        ),
    ]
