# Generated by Django 5.1.7 on 2025-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_artikel_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
