# Generated by Django 5.1.7 on 2025-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_artikel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
