# Generated by Django 5.1.7 on 2025-04-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_alter_artikel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
