# Generated by Django 5.2 on 2025-06-06 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_termin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termin',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='termin',
            name='datetime',
        ),
        migrations.AddField(
            model_name='termin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termin',
            name='endtime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termin',
            name='starttime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
